
import { Briefcase } from 'lucide-react';
import Link from 'next/link';

export default function PrivacyPolicyPage() {
  return (
    <div className="flex min-h-screen w-full justify-center bg-muted/40 p-4 sm:p-6 md:p-8">
      <div className="w-full max-w-4xl">
        <div className="mb-8 flex justify-center">
          <Link
            href="/"
            className="flex items-center gap-2 text-2xl font-bold text-primary"
          >
            <Briefcase className="h-7 w-7" />
            RecruitTrack
          </Link>
        </div>
        <div className="prose prose-gray mx-auto dark:prose-invert">
            <h1>Privacy Policy</h1>
            <p><strong>Last Updated:</strong> {new Date().toLocaleDateString()}</p>

            <h2>1. Introduction</h2>
            <p>
                RecruitTrack ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our internal hiring platform (the "Service"). Please read this policy carefully.
            </p>

            <h2>2. Information We Collect</h2>
            <p>We may collect information about you in a variety of ways. The information we may collect on the Service includes:</p>
            <ul>
                <li>
                    <strong>Personal Data:</strong> Personally identifiable information, such as your name, email address, and department, that you voluntarily give to us when you register for the Service.
                </li>
                <li>
                    <strong>Candidate Data:</strong> Information submitted by or about candidates, including resumes, contact details, skills, and any notes or evaluations made during the hiring process. This includes any data generated by our AI analysis features.
                </li>
                <li>
                    <strong>Usage Data:</strong> Information our servers automatically collect when you access the Service, such as your IP address, your browser type, your operating system, your access times, and the pages you have viewed directly before and after accessing the Service.
                </li>
            </ul>

            <h2>3. Use of Your Information</h2>
            <p>Having accurate information about you permits us to provide you with a smooth, efficient, and customized experience. Specifically, we may use information collected about you via the Service to:</p>
            <ul>
                <li>Create and manage your account.</li>
                <li>Operate and maintain the recruitment and hiring processes within your organization.</li>
                <li>Analyze candidate resumes against job descriptions using our AI tools to provide match scores and insights.</li>
                <li>Monitor and analyze usage and trends to improve your experience with the Service.</li>
                <li>Ensure the security of our platform and prevent fraudulent activity.</li>
            </ul>
            
            <h2>4. Disclosure of Your Information</h2>
            <p>
                We do not share your information with third parties outside of your organization. All data collected, including candidate data and AI analysis results, is for internal use only. We may disclose your information if we are required to do so by law or in response to valid requests by public authorities.
            </p>

            <h2>5. Data Security</h2>
            <p>
                We use administrative, technical, and physical security measures to help protect your personal information. While we have taken reasonable steps to secure the personal information you provide to us, please be aware that despite our efforts, no security measures are perfect or impenetrable, and no method of data transmission can be guaranteed against any interception or other type of misuse.
            </p>

            <h2>6. Use of Artificial Intelligence</h2>
            <p>
                Our Service utilizes AI to analyze candidate data. The text from resumes and job descriptions is processed by our AI models to generate match scores and reasoning. This data is processed for the sole purpose of providing this feature and is not used for training third-party models.
            </p>

            <h2>7. Your Data Rights</h2>
            <p>
                As this is an internal company tool, requests for data access, correction, or deletion should be directed to your company's HR or IT administrator, who manages the platform.
            </p>
            
            <h2>8. Changes to This Privacy Policy</h2>
            <p>
                We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.
            </p>

            <h2>9. Contact Us</h2>
            <p>
                If you have any questions or concerns about this Privacy Policy, please contact your internal administrator or reach out to us at <a href="mailto:support@leorecruit.com">support@leorecruit.com</a>.
            </p>
        </div>
      </div>
    </div>
  );
}
